name: Actualizar README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a la medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: npm install
    - run: npm run update-readme
      env:
        NODE_ENV: "development"
    - run: |
        git config user.name César P.
        git config user.email cesarlpb@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Actualizar README con progreso"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}