name: Actualizar README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a la medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: npm install
    - run: npm run update-readme
      env:
        NODE_ENV: "development"
    # Commit and push all changed files.
    - name: Create commit and push to repository
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "César P."
        git config --global user.email "cesarlpb@gmail.com"
        git add .
        git commit -m "[bot] Actualizar progreso"
        git push